travis:
  secure:
    BINSTAR_TOKEN: q71k/fYiey/OxKUBEW1uekpWcPRhIdIAlwT+qO+0oHP5Xdc1wrZ9UdI00S9MW3uOfdD6WoqJr/KSMEkq/NGNZh+RKOtTk+IpxyJ0hS0NpU54xNbypsAVwsoH0ky+wFVsIxmcStoKG4niZO3BxH9YS9fRCEV8DVbAAcFR98BkPUtSDRU4lQUnFIAQZ7Dd4CzQyLW220o896me27ichzM3kRxCCapPZhHkD0uIN6r295rdfhbU46MFMORbCc60dexGvohc+JYfUHKMtaYks39S5bXHocy3J1ve5ndDfFcxaY8o4czboK0EaZbw1FLfK/Deq02XHsMqv0vHiZ84dogmB+Ibw0yvH1vfaYGGGHB6AhPinxu9K6XCCjPky85vlgpp6GWOumE/wmvKvbtmTohuutTkgazgq7FSxpgcWpX3F5RzXkxRYRRJdI3HwaFK/tGKyRXO1bSX/RTtfeZ6pyFW44XxWFoMgnPXWbS31OQdN1QXnSm3Y6u6Eiiyg0VoNA0WvMf3susJ4IXlaxa+94m6dFLX2qIwOV2TaI0FvBpUHUrALHd8D5wivj6BZw2zt6JAiAjQD9vVsCkDTbAoODblPbDicU62Ox9TlvrOhanTc8aqTHV2Zz9EU+vV4vldCTt0/CM2CqhxM13gFiYaovXbjQOvvc8eATkgxd3USxG1m38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
